---
__default__:
  time: "00:10"
  threads: 1
  mem: 2000
  queue: debug
  error: "logs/%x_%j_%N.err"
  output: "logs/%x_%j_%N.log"
createSingleFeatureVCF:
  time: "200:00"
  mem: 10000
  queue: long
indexSingleFeatreVCF:
  time: "01:00"
mergeSingleFeatureVCF:
  time: "72:00"
  mem: 20000
  queue: medium
getPriPhyloP:
  time: "12:00"
  mem: 2000
  queue: medium
getPriPhastCons:
  time: "12:00"
  mem: 2000
  queue: medium
getPerPhyloP:
  time: "12:00"
  mem: 2000
  queue: medium
getVerPhastCons:
  time: "12:00"
  mem: 2000
  queue: medium
getMamPhastCons:
  time: "12:00"
  mem: 2000
  queue: medium
getMamPhyloP:
  time: "12:00"
  mem: 2000
  queue: medium
get_GCContent:
  time: "12:00"
  mem: 10000
  queue: medium
get_feature_1KG:
  time: "12:00"
  mem: 10000
  queue: medium
convert_feature_1kG:
  time: "12:00"
  mem: 10000
  queue: medium
get_feature_EncH3K4Me3:
  time: "12:00"
  mem: 10000
  queue: medium
get_feature_EncH3K4Me1:
  time: "12:00"
  mem: 10000
  queue: medium
get_feature_EncH3K27Ac:
  time: "12:00"
  mem: 10000
  queue: medium
convert_bigwig_to_wig:
  time: "12:00"
  mem: 10000
  queue: medium
get_feature_Intervals:
  time: "120:00"
  mem: 10000
  queue: medium
get_feature_Intervals_numTFBSConserved:
  time: "120:00"
  mem: 1000
  queue: medium
variants_annotateJannovar:
  time: "01:00"
  mem: 10000
  queue: medium
annotateFeatures:
  time: "200:00"
  mem: 10000
  queue: long
runParSMURF:
  time: "12:00"
  mem: 150000
  queue: medium
getReMM:
  time: "12:00"
  mem: 150000
  queue: medium
get_feature_Intervals_DGVCount:
  time: "12:00"
  mem: 150000
  queue: medium
annotateFeaturesRandom:
  time: "168:00"
  mem: 10000
  queue: medium

runParSMURFPredict:
  time: "12:00"
  mem: 150000
  queue: medium

getConservation:
  time: "120:00"
  mem: 10000
  queue: medium

convertToBigWig:
  time: "120:00"
  mem: 170000
  queue: medium

createPropertyFile19:
  time: "120:00"
  mem: 1000
  queue: medium

annotateFeatures38:
  time: "12:00"
  mem: 150000
  queue: medium
annotateFeatures19:
  time: "12:00"
  mem: 150000
  queue: medium

get_feature_1KG_19:
  time: "12:00"
  mem: 150000
  queue: medium
getRemmScore:
  time: "12:00"
  mem: 200000
  queue: medium
