---
global_files:
  genome_builds:
    hg38:
      reference: "/fast/projects/cubit/current/static_data/reference/GRCh38/hs38/hs38.fa"
      genome: "/fast/projects/cubit/current/static_data/reference/GRCh38/hs38/hs38.fa.genome"
    hg19:
      reference: "/fast/projects/cubit/current/static_data/reference/hg19/ucsc/hg19.fa"
      genome: "/fast/projects/cubit/current/static_data/reference/hg19/ucsc/hg19.fa.genome"
feature_sets:
  remm_v1_3_hg38:
    genome_build: hg38
    features:
      - CpGperGC
      - CpGperCpG
      - CpGobsExp
      - GCContent
      - priPhyloP
      - priPhastCons
      - verPhyloP
      - verPhastCons
      - mamPhyloP
      - mamPhastCons
      - EncH3K27Ac
      - EncH3K4Me1
      - EncH3K4Me3
      - DnaseClusteredHyp
      - DnaseClusteredScore
      - Fantom5Perm
      - Fantom5Robust
      - GerpRS
      - GerpRSpv
      - rareVar
      - commonVar
      - fracRareCommon
      - dbVARCount
      - ISCApath
      - DGVCount
      - numTFBSConserved
variants:
  cadd_v1_3_humanDerived_hg38:
    file: resources/variants/cadd_v1_3_humanDerived_hg38.vcf.gz
    genome_build: hg38
    jannovar: hg38_refseq
    filters:
      bcftools:
        filter: -i 'INFO/ANN~"|3_prime_UTR_intron_variant|" || INFO/ANN~"|5_prime_UTR_intron_variant|" || INFO/ANN~"|3_prime_UTR_exon_variant|" || INFO/ANN~"|5_prime_UTR_exon_variant|" || INFO/ANN~"|non_coding_transcript_intron_variant|" || INFO/ANN~"|non_coding_transcript_exon_variant|" || INFO/ANN~"|coding_transcript_intron_variant|" || INFO/ANN~"|upstream_gene_variant|" || INFO/ANN~"|downstream_gene_variant|" || INFO/ANN~"|intergenic_variant|" || INFO/ANN~"|splice_donor_variant|" || INFO/ANN~"|splice_acceptor_variant|" || INFO/ANN~"|splice_region_variant|"'
  remm_snvs_20160109_liftover:
    file: resources/variants/SNVs.all.20160109.vcf.gz
    liftover: hg19ToHg38
    genome_build: hg19
